"""trabalho itens (especialidades por trabalho)

Revision ID: 0272bba8888e
Revises: 0d811cf59ced
Create Date: 2026-09-02 23:48:03.986170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0272bba8888e'
down_revision: Union[str, None] = '0d811cf59ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabalho_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabalho_id', sa.Integer(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=True),
    sa.Column('externo_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_externo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_adjudicacao', sa.Date(), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['externo_id'], ['externos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trabalho_id'], ['trabalhos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trabalho_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trabalho_itens_data_adjudicacao'), ['data_adjudicacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_trabalho_itens_trabalho_id'), ['trabalho_id'], unique=False)

    # Nota: em SQLite o batch mode recria a tabela; as FKs antigas (sem nome)
    # desaparecem automaticamente ao remover as colunas, por isso não é preciso
    # (nem possível) fazer drop_constraint explícito das foreign keys.
    with op.batch_alter_table('trabalhos', schema=None) as batch_op:
        batch_op.drop_index('ix_trabalhos_data_adjudicacao')
        batch_op.drop_column('especialidade_id')
        batch_op.drop_column('data_entrega')
        batch_op.drop_column('data_adjudicacao')
        batch_op.drop_column('valor')
        batch_op.drop_column('valor_externo')
        batch_op.drop_column('externo_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('externo_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('valor_externo', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valor', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('data_adjudicacao', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('data_entrega', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('especialidade_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'especialidades', ['especialidade_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'externos', ['externo_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_trabalhos_data_adjudicacao', ['data_adjudicacao'], unique=False)

    with op.batch_alter_table('trabalho_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabalho_itens_trabalho_id'))
        batch_op.drop_index(batch_op.f('ix_trabalho_itens_data_adjudicacao'))

    op.drop_table('trabalho_itens')
    # ### end Alembic commands ###
