"""trabalho itens (especialidades por trabalho)

Revision ID: 0272bba8888e
Revises: 0d811cf59ced
Create Date: 2026-09-02 23:48:03.986170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0272bba8888e'
down_revision: Union[str, None] = '0d811cf59ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _largar_fks_mysql(bind, tabela: str, colunas: list[str]) -> None:
    """Descobre e larga as foreign keys do MySQL que referenciam as colunas dadas.

    Necessário porque o MySQL não deixa remover uma coluna enquanto existir uma FK
    que dependa dela (erro 1828). Os nomes das FKs são gerados automaticamente
    (ex.: trabalhos_ibfk_1), por isso descobrimo-los no information_schema.
    """
    for coluna in colunas:
        nomes = bind.exec_driver_sql(
            """
            SELECT constraint_name
            FROM information_schema.key_column_usage
            WHERE table_schema = DATABASE()
              AND table_name = %s
              AND column_name = %s
              AND referenced_table_name IS NOT NULL
            """,
            (tabela, coluna),
        ).fetchall()
        for (nome,) in nomes:
            op.drop_constraint(nome, tabela, type_="foreignkey")


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Idempotente: criar a tabela só se ainda não existir (protege contra
    # execuções parciais anteriores, comuns no MySQL onde o DDL não faz rollback).
    if "trabalho_itens" not in inspector.get_table_names():
        op.create_table('trabalho_itens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('trabalho_id', sa.Integer(), nullable=False),
        sa.Column('especialidade_id', sa.Integer(), nullable=True),
        sa.Column('externo_id', sa.Integer(), nullable=True),
        sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('valor_externo', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('data_adjudicacao', sa.Date(), nullable=True),
        sa.Column('data_entrega', sa.Date(), nullable=True),
        sa.Column('observacoes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['externo_id'], ['externos.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['trabalho_id'], ['trabalhos.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('trabalho_itens', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_trabalho_itens_data_adjudicacao'), ['data_adjudicacao'], unique=False)
            batch_op.create_index(batch_op.f('ix_trabalho_itens_trabalho_id'), ['trabalho_id'], unique=False)

    # Colunas antigas de 'trabalhos' que passam para os itens.
    colunas_trabalhos = {c["name"] for c in inspector.get_columns("trabalhos")}
    a_remover = ["especialidade_id", "data_entrega", "data_adjudicacao", "valor", "valor_externo", "externo_id"]

    if bind.dialect.name == "mysql":
        # No MySQL, largar as FKs (e o índice) antes de remover as colunas.
        _largar_fks_mysql(bind, "trabalhos", ["especialidade_id", "externo_id"])
        indices = {i["name"] for i in inspector.get_indexes("trabalhos")}
        if "ix_trabalhos_data_adjudicacao" in indices:
            op.drop_index("ix_trabalhos_data_adjudicacao", table_name="trabalhos")
        for col in a_remover:
            if col in colunas_trabalhos:
                op.drop_column("trabalhos", col)
    else:
        # Em SQLite, o batch mode recria a tabela; as FKs desaparecem sozinhas.
        with op.batch_alter_table("trabalhos", schema=None) as batch_op:
            batch_op.drop_index("ix_trabalhos_data_adjudicacao")
            for col in a_remover:
                if col in colunas_trabalhos:
                    batch_op.drop_column(col)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('externo_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('valor_externo', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valor', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('data_adjudicacao', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('data_entrega', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('especialidade_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'especialidades', ['especialidade_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'externos', ['externo_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('ix_trabalhos_data_adjudicacao', ['data_adjudicacao'], unique=False)

    with op.batch_alter_table('trabalho_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabalho_itens_trabalho_id'))
        batch_op.drop_index(batch_op.f('ix_trabalho_itens_data_adjudicacao'))

    op.drop_table('trabalho_itens')
    # ### end Alembic commands ###
