"""custos anuais e equipamentos

Revision ID: 0d811cf59ced
Revises: 9b9fabbeac64
Create Date: 2026-09-02 17:56:12.708362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d811cf59ced'
down_revision: Union[str, None] = '9b9fabbeac64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custos_anuais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custos_anuais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custos_anuais_ano'), ['ano'], unique=False)

    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('percentagem', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('ano_aquisicao', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipamentos')
    with op.batch_alter_table('custos_anuais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custos_anuais_ano'))

    op.drop_table('custos_anuais')
    # ### end Alembic commands ###
