"""tabela trabalhos

Revision ID: 808622b3cd95
Revises: 9ef066e89b0a
Create Date: 2026-09-02 17:43:09.312182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808622b3cd95'
down_revision: Union[str, None] = '9ef066e89b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabalhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=50), nullable=True),
    sa.Column('cliente', sa.String(length=255), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('localidade', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('intermediario_id', sa.Integer(), nullable=True),
    sa.Column('especialidade_id', sa.Integer(), nullable=True),
    sa.Column('externo_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_externo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_adjudicacao', sa.Date(), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['externo_id'], ['externos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intermediario_id'], ['intermediarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trabalhos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trabalhos_cliente'), ['cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_trabalhos_data_adjudicacao'), ['data_adjudicacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_trabalhos_referencia'), ['referencia'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalhos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabalhos_referencia'))
        batch_op.drop_index(batch_op.f('ix_trabalhos_data_adjudicacao'))
        batch_op.drop_index(batch_op.f('ix_trabalhos_cliente'))

    op.drop_table('trabalhos')
    # ### end Alembic commands ###
