"""tabelas de apoio

Revision ID: 9ef066e89b0a
Revises: 
Create Date: 2026-09-02 17:36:14.974129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef066e89b0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('prazo_top', sa.Integer(), nullable=False),
    sa.Column('prazo_ok', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('especialidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_especialidades_codigo'), ['codigo'], unique=True)

    op.create_table('externos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('externos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_externos_nome'), ['nome'], unique=True)

    op.create_table('intermediarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intermediarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intermediarios_nome'), ['nome'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intermediarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intermediarios_nome'))

    op.drop_table('intermediarios')
    with op.batch_alter_table('externos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_externos_nome'))

    op.drop_table('externos')
    with op.batch_alter_table('especialidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_especialidades_codigo'))

    op.drop_table('especialidades')
    # ### end Alembic commands ###
