"""situacao no trabalho item

Revision ID: f16050410dff
Revises: 0272bba8888e
Create Date: 2026-09-03 12:18:07.322186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16050410dff'
down_revision: Union[str, None] = '0272bba8888e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalho_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situacao', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabalho_itens', schema=None) as batch_op:
        batch_op.drop_column('situacao')

    # ### end Alembic commands ###
